#+DATE: 2017-11-27 06:45
#+PROPERTY: SLUG falafel
#+PROPERTY: TAGS veg
#+TITLE: Falafel di ceci


Per la preparazione dei falafel a partire dai ceci essiccati sarà necessario
procedere al loro ammollo in acqua per 24 ore. L'acqua dell'ammollo dovrà essere
sostituita dopo 12 ore. Ricordate che non dovrete procedere alla cottura dei
ceci prima di realizzare le crocchette. Per formare i falafel è infatti
necessario partire da ceci crudi.

Una volta trascorso il tempo dell'ammollo, i ceci dovranno essere scolati
completamente e riposti nel bicchiere di un mixer da cucina. All'interno di esso
dovranno essere aggiunte la cipolla tritata, lo spicchio d'aglio (di cui potete
fare a meno, se non ne amate il gusto), il prezzemolo, il cumino e un filo
d'olio extravergine d'oliva.

Procedete frullando il tutto fino ad ottenere un composto omogeneo. Regolatene
il sapore con il sale e con il pepe e iniziate a formare con le mani delle
crocchette di forma sferica, oppure appiattita. Solamente nel caso in cui il
composto dovesse risultare troppo morbido, aggiungete un pochino di pane
grattugiato o di farina di ceci.

Per facilitare la formazione delle crocchette e ottenere un impasto più
compatto, è inoltre consigliabile lasciare riposare l'impasto in frigorifero per
un'ora, prima di mettervi all'opera. Una volta formate le crocchette di ceci,
sarà necessario procedere alla loro cottura. La ricetta tradizionale dei falafel
prevede che venga effettuata la loro frittura in olio bollente, da prolungare
fino al momento in cui la superficie delle crocchette non risulterà ben dorata.

Esiste però un'alternativa alla frittura, che renderà i vostri falafel di ceci
molto più leggeri. Si tratta della cottura al forno, che può essere effettuata
senza l'aggiunta di grassi, ad eccezione di un pochino d'olio per ungere la
teglia, a meno che non si utilizzi della carta da forno. La cottura in forno
avrà una durata di circa 20-25 minuti a 180 °C.

I falafel di ceci al forno saranno pronti quando sulla loro superficie si sarà
formata una crosticina croccante e ben dorata. Sono ottimi se accompagnati anche
da hummus di ceci o dalla sala allo yogurt.

** Materials (10-15 falafel)
   
    - 250 grammi di ceci essiccati
    - 2 cucchiai di prezzemolo tritato
    - Farina di ceci o pane grattugiato
    - Olio extravergine d'oliva
    - 1 spicchio d'aglio
    - ½ cucchiaino di cumino in polvere
    - ½ cipolla
    - Sale e pepe

** references

https://www.greenme.it/mangiare/vegetariano-a-vegano/9412-falafel-ricetta
