#+TITLE: Pita
#+DATE: 2017-11-25 16:16

Versate la farina in una ciotola grande, aggiungete il sale, lo zucchero e il
lievito in polvere, mescolate per distribuire gli ingredienti in modo uniforme;
poi aggiungete l'olio d'oliva, mescolate bene con un cucchiaio di legno e
versate a filo le due tazze di acqua tiepida.

Mescolate ancora, con il vostro cucchiaio di legno, fino ad ottenere un impasto
molto morbido, che risulterà più colloso ed elastico rispetto a quello che
ottenete durante la preparazione del pane o della pizza.

Lasciate riposare qualche minuto e quando vedete delle bolle sulla superficie
della pasta, rimpastatela per qualche minuto, poi copritela con un panno e fate
lievitare per circa 2 ore.

A questo punto – aiutandovi con un po’ di farina per rendere l’impasto meno
colloso - dividete la pasta in 20 palline e lavoratene una per volta: stendete
la pasta su un piano da lavoro infarinato e fatene una pizzetta del diametro di
almeno 20 cm. Poi scaldate una padella che abbia più o meno lo stesso diametro
(l’ideale sarebbe utilizzare le padelle fatte appositamente per la cottura della
pita che hanno un coperchio spesso con all’interno una resistenza, in modo da
far cuocere il pane in modo uniforme).

** Materials

- 1 kg di farina setacciata
- 1 cucchiaino di sale
- 1/2 cucchiaino di zucchero
- 1 cucchiaio di olio di oliva
- 1/2 cucchiaino di lievito in polvere
- 2 tazze d'acqua tiepida (90%)

** references

https://www.greenme.it/mangiare/cucina/5197-come-fare-il-pane-pita-in-casa
