#+TITLE: Pita
#+DATE: 2017-11-21

Versate la farina in una ciotola grande, aggiungete il sale, lo zucchero e il lievito in polvere, mescolate per distribuire gli ingredienti in modo uniforme; poi aggiungete l'olio d'oliva, mescolate bene con un cucchiaio di legno e versate a filo le due tazze di acqua tiepida.

Mescolate ancora, con il vostro cucchiaio di legno, fino ad ottenere un impasto molto morbido, che risulterà più colloso ed elastico rispetto a quello che ottenete durante la preparazione del pane o della pizza.

procedimento_pita

Lasciate riposare qualche minuto e quando vedete delle bolle sulla superficie della pasta, rimpastatela per qualche minuto, poi copritela con un panno e fate lievitare per circa 2 ore.

A questo punto – aiutandovi con un po’ di farina per rendere l’impasto meno colloso - dividete la pasta in 20 palline e lavoratene una per volta: stendete la pasta su un piano da lavoro infarinato e fatene una pizzetta del diametro di almeno 20 cm.
Poi scaldate una padella che abbia più o meno lo stesso diametro (l’ideale sarebbe utilizzare le padelle fatte appositamente per la cottura della pita che hanno un coperchio spesso con all’interno una resistenza, in modo da far cuocere il pane in modo uniforme).

Preparazione

Per la preparazione dei falafel a partire dai ceci essiccati sarà necessario procedere al loro ammollo in acqua per 24 ore. L'acqua dell'ammollo dovrà essere sostituita dopo 12 ore. Ricordate che non dovrete procedere alla cottura dei ceci prima di realizzare le crocchette. Per formare i falafel è infatti necessario partire da ceci crudi.

Una volta trascorso il tempo dell'ammollo, i ceci dovranno essere scolati completamente e riposti nel bicchiere di un mixer da cucina. All'interno di esso dovranno essere aggiunte la cipolla tritata, lo spicchio d'aglio (di cui potete fare a meno, se non ne amate il gusto), il prezzemolo, il cumino e un filo d'olio extravergine d'oliva.

Procedete frullando il tutto fino ad ottenere un composto omogeneo. Regolatene il sapore con il sale e con il pepe e iniziate a formare con le mani delle crocchette di forma sferica, oppure appiattita. Solamente nel caso in cui il composto dovesse risultare troppo morbido, aggiungete un pochino di pane grattugiato o di farina di ceci.

Per facilitare la formazione delle crocchette e ottenere un impasto più compatto, è inoltre consigliabile lasciare riposare l'impasto in frigorifero per un'ora, prima di mettervi all'opera. Una volta formate le crocchette di ceci, sarà necessario procedere alla loro cottura. La ricetta tradizionale dei falafel prevede che venga effettuata la loro frittura in olio bollente, da prolungare fino al momento in cui la superficie delle crocchette non risulterà ben dorata.

Esiste però un'alternativa alla frittura, che renderà i vostri falafel di ceci molto più leggeri. Si tratta della cottura al forno, che può essere effettuata senza l'aggiunta di grassi, ad eccezione di un pochino d'olio per ungere la teglia, a meno che non si utilizzi della carta da forno. La cottura in forno avrà una durata di circa 20-25 minuti a 180 °C.

I falafel di ceci al forno saranno pronti quando sulla loro superficie si sarà formata una crosticina croccante e ben dorata. Sono ottimi se accompagnati anche da hummus di ceci o dalla sala allo yogurt.
** aaa

1. Sbucciate le mele e tagliatene due a pezzetti e l'ultima a fettine
   regolari per la copertura (se preferite le fette di mela anche
   all'interno, tagliatele tutte a fette, ovviamente).
2. Pre-riscaldate il forno a 180°C.
3. Lavorate lo yogurt con lo zucchero e le uova, poi unite la farina, il
   lievito (o la farina autolievitante), i pezzetti (o le fettine) di
   due mele (io infarino prima i pezzi di mela, per evitare che cadano
   tutti sul fondo in cottura), la vaniglia (se la gradite) e la scorza
   grattugiata del limone.
4. Imburrate e infarinate una teglia e versate al suo interno il
   composto. Coprite quindi con le fettine dell'ultima mela disposte in
   modo concentrico (o come più preferite). Spolverate poi la superficie
   con due cucchiai di zucchero e disponete, da ultimo, qualche ricciolo
   di burro.
5. Cuocere in forno caldo per circa un'ora (stando attenti che le mele
   non si brucino e facendo la prova stecchino per la cottura interna).

** Materials (10-15 falafel)
   
    - 250 grammi di ceci essiccati
    - 2 cucchiai di prezzemolo tritato
    - Farina di ceci o pane grattugiato
    - Olio extravergine d'oliva
    - 1 spicchio d'aglio
    - ½ cucchiaino di cumino in polvere
    - ½ cipolla
    - Sale e pepe


    1 kg di farina setacciata
    1 cucchiaino di sale
    1/2 cucchiaino di zucchero
    1 cucchiaio di olio di oliva
    1/2 cucchiaino di lievito in polvere
    2 tazze d'acqua tiepida

** references

https://www.greenme.it/mangiare/cucina/5197-come-fare-il-pane-pita-in-casa
