name: deploy

# Only run this when the master branch changes
on:
  push:
    branches:
      - main
      # paths:
      # - some-subfolder/**

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install pandoc
        run: |
          sudo apt-get install -y pandoc
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version
          pip install -r .github/workflows/constraints.txt
      - name: Build pages
        run: |
          pelican

    # # Push the book's HTML to github-pages
    # - name: GitHub Pages action
    #   uses: peaceiris/actions-gh-pages@v3.6.1
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./output

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'output/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

